// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUh9uHWL04NXiqzAazzN-w38PG0rY3PCU',
    appId: '1:900806889390:web:cc70ecc2fbf327dc90423f',
    messagingSenderId: '900806889390',
    projectId: 'flutter-project-7777',
    authDomain: 'flutter-project-7777.firebaseapp.com',
    storageBucket: 'flutter-project-7777.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgo7hF0e_rTu4CLJtQXcpa1imWk35g4gs',
    appId: '1:900806889390:android:5406fc839bd1887a90423f',
    messagingSenderId: '900806889390',
    projectId: 'flutter-project-7777',
    storageBucket: 'flutter-project-7777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzryx03ij4iOmKWas_VhsEKjj1FNmWVo',
    appId: '1:900806889390:ios:a3cb8d392cb1737f90423f',
    messagingSenderId: '900806889390',
    projectId: 'flutter-project-7777',
    storageBucket: 'flutter-project-7777.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzryx03ij4iOmKWas_VhsEKjj1FNmWVo',
    appId: '1:900806889390:ios:5bad2ca462c451aa90423f',
    messagingSenderId: '900806889390',
    projectId: 'flutter-project-7777',
    storageBucket: 'flutter-project-7777.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
